import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Carti pentru copii</title>
      </head>
      <body className={inter.className}>
        <div className="ml-auto mr-auto w-full max-w-[720px]">
          <div className="pl-4 pr-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
